select
        distinct idocesitib0_.ID as ID1_0_,
        idocesitib0_.ANNULLATO as ANNULLAT2_0_,
        idocesitib0_.CDATE as CDATE3_0_,
        idocesitib0_.CIN as CIN4_0_,
        idocesitib0_.CIN_MAGAZZINO as CIN_MAGA5_0_,
        idocesitib0_.COD_DICHIARANTE as COD_DICH6_0_,
        idocesitib0_.COD_LUOGO_CONSEGNA as COD_LUOG7_0_,
        idocesitib0_.CODICE as CODICE8_0_,
        idocesitib0_.CODICE_REGISTRO as CODICE_R9_0_,
        idocesitib0_.CODICE_SVINCOLO as CODICE_10_0_,
        idocesitib0_.COLLI as COLLI11_0_,
        idocesitib0_.CONDIZIONE_CONSEGNA as CONDIZI12_0_,
        idocesitib0_.CONTENITORI as CONTENI13_0_,
        idocesitib0_.DATA_REGISTRAZIONE as DATA_RE14_0_,
        idocesitib0_.DATI_CARICO as DATI_CA15_0_,
        idocesitib0_.DESTINATARIO as DESTINA16_0_,
        idocesitib0_.DESTINATARIO_CAP as DESTINA17_0_,
        idocesitib0_.DESTINATARIO_CITTA as DESTINA18_0_,
        idocesitib0_.DESTINATARIO_INDIRIZZO as DESTINA19_0_,
        idocesitib0_.DESTINATARIO_PAESE as DESTINA20_0_,
        idocesitib0_.DESTINATARIO_PIVA as DESTINA21_0_,
        idocesitib0_.DICHIARANTE as DICHIAR22_0_,
        idocesitib0_.DICHIARANTE_CAP as DICHIAR23_0_,
        idocesitib0_.DICHIARANTE_CITTA as DICHIAR24_0_,
        idocesitib0_.DICHIARANTE_INDIRIZZO as DICHIAR25_0_,
        idocesitib0_.DICHIARANTE_PAESE as DICHIAR26_0_,
        idocesitib0_.ID_IDOC as ID_IDOC27_0_,
        idocesitib0_.ID_MAGAZZINO as ID_MAGA28_0_,
        idocesitib0_.LUOGO_ACCERTAMENTO_MERCI as LUOGO_A29_0_,
        idocesitib0_.LUOGO_CARICO_MERCI as LUOGO_C30_0_,
        idocesitib0_.LUOGO_CONSEGNA as LUOGO_C31_0_,
        idocesitib0_.IS_MANUAL as IS_MANU32_0_,
        idocesitib0_.MEZZO_TRASPORTO as MEZZO_T33_0_,
        idocesitib0_.MEZZO_TRASPORTO_FRONTIERA as MEZZO_T34_0_,
        idocesitib0_.MODO_TRASPORTO_FRONTIERA as MODO_TR35_0_,
        idocesitib0_.MODO_TRASPORTO_INTERNO as MODO_TR36_0_,
        idocesitib0_.MRN as MRN37_0_,
        idocesitib0_.NATURA_TRANSAZIONE as NATURA_38_0_,
        idocesitib0_.NAZIONALITA_MEZZO_TRASPORTO as NAZIONA39_0_,
        idocesitib0_.NAZIONALITA_MEZZO_TRASPORTO_FRONTIERA as NAZIONA40_0_,
        idocesitib0_.NUM_AUTORIZZAZIONE as NUM_AUT41_0_,
        idocesitib0_.NUMERO_REGISTRAZIONE as NUMERO_42_0_,
        idocesitib0_.NUMERO_RIFERIMENTO as NUMERO_43_0_,
        idocesitib0_.OBBLIGATO_PRINCIPALE as OBBLIGA44_0_,
        idocesitib0_.OBBLIGATO_PRINCIPALE_CAP as OBBLIGA45_0_,
        idocesitib0_.OBBLIGATO_PRINCIPALE_CITTA as OBBLIGA46_0_,
        idocesitib0_.OBBLIGATO_PRINCIPALE_INDIRIZZO as OBBLIGA47_0_,
        idocesitib0_.OBBLIGATO_PRINCIPALE_PAESE as OBBLIGA48_0_,
        idocesitib0_.OBBLIGATO_PRINCIPALE_PIVA as OBBLIGA49_0_,
        idocesitib0_.PAESE_DESTINAZIONE as PAESE_D50_0_,
        idocesitib0_.PAESE_SPEDIZIONE as PAESE_S51_0_,
        idocesitib0_.PESO_LORDO as PESO_LO52_0_,
        idocesitib0_.PROGRESSIVO as PROGRES53_0_,
        idocesitib0_.PROGRESSIVO_PRATICA as PROGRES54_0_,
        idocesitib0_.RAPPRESENTANTE as RAPPRES55_0_,
        idocesitib0_.SERIE_REGISTRO as SERIE_R56_0_,
        idocesitib0_.SEZIONE_DOGANALE as SEZIONE57_0_,
        idocesitib0_.SPEDIZIONIERE as SPEDIZI58_0_,
        idocesitib0_.SPEDIZIONIERE_CAP as SPEDIZI59_0_,
        idocesitib0_.SPEDIZIONIERE_CITTA as SPEDIZI60_0_,
        idocesitib0_.SPEDIZIONIERE_INDIRIZZO as SPEDIZI61_0_,
        idocesitib0_.SPEDIZIONIERE_PAESE as SPEDIZI62_0_,
        idocesitib0_.SPEDIZIONIERE_PIVA as SPEDIZI63_0_,
        idocesitib0_.SVINCOLATO as SVINCOL64_0_,
        idocesitib0_.SVINCOLO as SVINCOL65_0_,
        idocesitib0_.TASSO_CAMBIO as TASSO_C66_0_,
        idocesitib0_.TIPO as TIPO67_0_,
        idocesitib0_.TIPO_DICHIARAZIONE as TIPO_DI68_0_,
        idocesitib0_.TIPO_FORMULARIO as TIPO_FO69_0_,
        idocesitib0_.TIPO_RAPPRESENTANZA as TIPO_RA70_0_,
        idocesitib0_.TIPO_SPEDIZIONE as TIPO_SP71_0_,
        idocesitib0_.TOTALE_ARTICOLI as TOTALE_72_0_,
        idocesitib0_.TOTALE_COLLI as TOTALE_73_0_,
        idocesitib0_.TOTALE_DIRITTI as TOTALE_74_0_,
        idocesitib0_.TOTALE_FATTURATO as TOTALE_75_0_,
        idocesitib0_.TRASPORTO_IN_CONTAINER as TRASPOR76_0_,
        idocesitib0_.UFFICIO_DESTINAZIONE as UFFICIO77_0_,
        idocesitib0_.VALUTA_FATTURAZIONE as VALUTA_78_0_ 
    from
        HANDLING.IDOC_ESITI_BOLLE idocesitib0_ 
    left outer join
        HANDLING.IDOC_ESITI_DETTAGLIO dettagli1_ 
            on idocesitib0_.ID=dettagli1_.ID_ESITO 
    left outer join
        HANDLING.IDOC_ESITI_CONTAINERS containers2_ 
            on dettagli1_.ID=containers2_.ID_DETTAGLIO 
    where
        upper(containers2_.CODICE_CONTAINER)=upper('TGBU5711481') 
        and idocesitib0_.IS_MANUAL=1 
        and idocesitib0_.ANNULLATO<>1 
        and idocesitib0_.CDATE>='2019-08-22'
    order by
        idocesitib0_.ID DESC limit 100